### ISSUE TITLE
Is there a fix for this issue?

### ISSUE THREAD

**Issue by Mrdofbeer** [ProfessorJTJ/HISuite-Proxy#125]
Have myself a Mate 20 Pro LYA-L09 (C432) Wanted the VoLTE feature that version 11 doesn't have so downgraded to 10.1 successfully. Quickly found out that 10.1 doesn't have VoLTE so decided to OTA update to regain USB functionality. Got as far as 11.0.0.139 and can't go any further (Latest update installed) and still don't have USB or fast charging, thing is I know there are other updates to be had, my other 20 Pro has 11.0.0.172. Now I've tried an OTG downgrade to 10.0 but "Verifying Update" loops at 38% on both a Philips and Sandisk USB so I'm running out of idea's. Seems Huawei's petulance has the win!

Any thoughts?

**Comment by ProfessorJTJ** [comment]
There's an application in your phone called "support" open it, it has a section called "update" click on it, it might work.

If not boot to erecovery and try to update from there

**Comment by Mrdofbeer** [comment]
Hey Professor. Thanks for replying. Support/update returns "your firmware is upto date" and erecovery shows 11.0.0.139 as the latest update. 

I think unless I can find a firmware package higher than 11.0.0.139 it's going to be no Bueno. I'm kinda hoping a higher firmware will verify past 38% to 100%. I'll keep testing. Makes you wonder why Huawei make things so difficult...

**Comment by ProfessorJTJ** [comment]
Dload firmware installation through memory card might do the job

**Comment by Loggsie** [comment]
Yes. I have a potential fix and it's as simple as using an alternative USB-C cable to the one you used during the downgrade. I had the exact same issue when downgrading from EMUI 11 right back to EMUI 9. I lost functions upon reaching 10.1. However having used a different USB-C cable since and reverting to the original. I can confirm USB, fast boot and fast charge work. I am unable to confirm if this remedies test point.
