### ISSUE TITLE
Setup icon doesn't add on desktop

### ISSUE THREAD

**Issue by cesneris** [ProfessorJTJ/HISuite-Proxy#165]
Hey guys,

I am trying to roll back my P40 EMUI 12 to the older version but HiSuite Proxy doesn't create the new icon on the desktop. I add base, cust and preload like it should and I did this some time ago and it worked like a charm. But currently nothing happens. Setup window doesn't contain any errors, it says I'm ready to proceed to installation.

Can it be related to Windows 11?

Thanks.

**Comment by ProfessorJTJ** [comment]
Hi, open hisuite's folder in C drive.

C:/Program files(86)/HiSuite

See if there's a hisuite there with the name HiSuite 11.exe if so, just use that one. 

By the way, as far as I'm concerned stable EMUI 12, blocks downgrades to emui 10...

**Comment by cesneris** [comment]
There's no HiSuite 11.exe there either. Well, I guess that could be true. Is there any other way to downgrade to 10.1.0.131?

**Comment by ProfessorJTJ** [comment]
What version of hisuite do you have installed?

**Comment by cesneris** [comment]
I've got Hisuite_10.1.0.550_OVE

**Comment by ProfessorJTJ** [comment]
> I've got Hisuite_10.1.0.550_OVE

Just use the green hisuite you don't need to use another one.

**Comment by cesneris** [comment]
Oh, it actually worked. It showed me update for 10.1.0.131 version. Thank you, will try it.

**Comment by odzoski88** [comment]
which one is that, the green hisuite..i have a problem with p40 pro and emui 12...

**Comment by ProfessorJTJ** [comment]
> which one is that, the green hisuite..i have a problem with p40 pro and emui 12...

If you're using hisuite 10.1 you don't need to use red icon hisuite just use the green one.

Otherwise if you're on hisuite 11, use hisuite 11.exe in C:/Program files(86x)/HiSuite

HiSuite 10.1
https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

HiSuite 11.0.0.530
https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.6/HiSuite_11.0.0.530_OVE.rar
