### ISSUE TITLE
firm mismatch error

### ISSUE THREAD

**Issue by VoodooMild** [ProfessorJTJ/HISuite-Proxy#211]
Im getting this error when it looks like i have the proper firmware selected. i dont have the one selected that its saying i do. i dont think so anyways. photos attached of error and log fil
[mate 20proSystemUpdate_20220508_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/8648778/mate.20proSystemUpdate_20220508_00.log)
![PXL_20220509_042406220](https://user-images.githubusercontent.com/60105867/167341407-930472b0-49fa-4759-97bf-e4e2d00751d0.jpg)
![PXL_20220509_042355973](https://user-images.githubusercontent.com/60105867/167341417-3eb6962e-64ad-4803-95ac-c142b55e1252.jpg)
e

**Comment by ProfessorJTJ** [comment]
Hello, the ids passed for the roms were incorrect, now my assumption is, you've opened "Advanced" section, "Customaziation" and used custom base and custom preload ids ( because I see your cust id is right and only the other two packages were overridden by that section's feature )

![Screenshot 2022-04-15 132440](https://user-images.githubusercontent.com/49002275/167349502-1492381e-35f9-450f-b0a9-efe5b5d17fa3.png)

just close, reopen the app, add your roms, and don't play with the settings.

**Comment by VoodooMild** [comment]
ok yes i did change them trying something and i for  got to change them back thank you
