### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by snajlcz** [ProfessorJTJ/HISuite-Proxy#4]
Hi, i have a Mate 10 Pro C432, i succesfull Updated in huisuite, after install in phone say " verify ...." Software install failed. 

```
http://update.dbankcdn.com/TDS/data/files/p3/s15/G5398/g1755/v400939/f1/ BLA-LGRP2-OVS 10.0.0.159
http://update.dbankcdn.com/TDS/data/files/p3/s15/G5398/g1755/v386370/f1/  BLA-L29-CUST 10.0.0.5(C432)
http://update.dbankcdn.com/TDS/data/files/p3/s15/G5398/g1755/v386373/f1/ BLA-L29-PRELOAD 10.0.0.3(C432R1)

```

**Comment by ProfessorJTJ** [comment]
That's because your CUST and Preload packages are not approved for installation use those

PRELOAD
http://update.dbankcdn.com/TDS/data/files/p3/s15/G5398/g1755/v401470/f1/full/changelog_preload_hw_eu_R1.xml

CUST
http://update.dbankcdn.com/TDS/data/files/p3/s15/G5398/g1755/v401407/f1/full/changelog_cust_hw_eu.xml

**Comment by snajlcz** [comment]
Sorry my mistakes. thank you
