### ISSUE TITLE
Offline files selection

### ISSUE THREAD

**Issue by JozinekCZ** [ProfessorJTJ/HISuite-Proxy#68]
Every time i try to select offline files for flashing, i got error saying - there is not end of root directory. I already downloaded files from other source so i cannot use url. Device Mate 10 Pro, i have all three files, but same error every time doesnt matter which one i select first. Windows 10 devíce, HiSuite Proxy run as administrator.

**Comment by ProfessorJTJ** [comment]
> Every time i try to select offline files for flashing, i got error saying - there is not end of root directory. I already downloaded files from other source so i cannot use url. Device Mate 10 Pro, i have all three files, but same error every time doesnt matter which one i select first. Windows 10 devíce, HiSuite Proxy run as administrator.

You still cannot install the roms unless you know their version id, I made that offline package thing because Huawei changed its OTA system, but I managed to grab the firmwares and so I updated hisuite proxy to v2 and created an integrated website to allow people to flash firmwares once again, offline packages is so fragile and is a pain in the butt to get it working, so I'd advise you to use the website and let hisuite download the packages

https://www.firmfinder.ml

**Comment by JozinekCZ** [comment]
Now it is clear. My files are not listed in firmfinder.ml, so it mean that i cannot use HiSuite Proxy

**Comment by ProfessorJTJ** [comment]
> Now it is clear. My files are not listed in firmfinder.ml, so it mean that i cannot use HiSuite Proxy

Open the 3 zip files you got, there is a file named VERSION, send these 3 version names in here so I can guide you


By the way, you can also read this guide
https://github.com/ProfessorJTJ/HISuite-Proxy/wiki/Complete-Guide

**Comment by JozinekCZ** [comment]
May i upload firmware somewhere and share link to you? As i dont find informations you request. BTW: i read complete Guide before i ask.

**Comment by ProfessorJTJ** [comment]
> May i upload firmware somewhere and share link to you? As i dont find informations you request. BTW: i read complete Guide before i ask.

Open the zip files using Winrar application
Then send a screenshot from the files list in that zip if you can't find a file named VERSION
