### ISSUE TITLE
Huawei P40 Lite soft brick restore

### ISSUE THREAD

**Issue by SharkSK31** [ProfessorJTJ/HISuite-Proxy#73]
Hello,

I did everything correctly, but I always receive error the device cant be repaired at 99% of installing recovery.

What is actually the problem? Incompatible FW?
I choosed the correct one on firmfinder.
It is a C432 JNY-L21
Can you help me out? 

Thanks

**Comment by ProfessorJTJ** [comment]
Hi, please attach your log file, it can be found at:
C:/Users/Your user/App data/local/HiSuite/log/systemupdate.log

**Comment by SharkSK31** [comment]
[SystemUpdate_20210702_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6754916/SystemUpdate_20210702_00.log)

**Comment by ProfessorJTJ** [comment]
*    FirmWare_Base:JNY-LGRP2-OVS 10.1.0.302
*    FirmWare_Cust:JNY-L21-CUST 10.1.0.1(C432)
*    FirmWare_Preload:JNY-L21-PRELOAD 10.1.0.1(C432R6)
* 
Your base version is 10.1.0.302, so you have to either use it, or use a version newer than it, you were adding base number 10.1.0.261 which in turn fails because is older than 302

try this rom combination:
JNY-LGRP2-OVS 10.1.0.302 : https://www.firmfinder.ml/521497
JNY-L21-CUST 10.1.0.1(C432) : https://www.firmfinder.ml/391120
JNY-L21-PRELOAD 10.1.0.1(C432R6) : https://www.firmfinder.ml/425210

**Comment by SharkSK31** [comment]
[SystemUpdate_20210702_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6755223/SystemUpdate_20210702_00.log)
DiagPort is no available What does it mean? That it cant start in secure boot?

**Comment by ProfessorJTJ** [comment]
> [SystemUpdate_20210702_00.log](https://github.com/ProfessorJTJ/HISuite-Proxy/files/6755223/SystemUpdate_20210702_00.log)
> DiagPort is no available What does it mean? That it cant start in secure boot?
> Btw tried with 302 aswell as with 331, same error

What version of hisuite are you using?
10.1 or 11?
Try to tick the box "Force Auth Bridge" in HiSuite proxy along with using Hisuite 10.1

https://github.com/ProfessorJTJ/HISuite-Proxy/releases/download/2.3.5/Hisuite_10.1.0.550_OVE.zip

**Comment by SharkSK31** [comment]
I reinstalled hisuite with this version a tick the force auth bridge,
Still same error.
I notice when it start to flash recovery the device get disconnected and then again connected, this is the time when in log shows that diagport is not available.
